[build-system]
requires = ["setuptools>=61.0", "requests", "bs4"]
build-backend = "setuptools.build_meta"

[project]
name = "mame_dl"
version = "0.1.0"
description = "MAME Download"
dynamic = ["entry-points"]